version: '{build}'
skip_tags: true
skip_commits:
  message: /\[ci skip\]/
clone_depth: 10
environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - set PATH=%JAVA_HOME%\bin;%PATH%
  - echo %PATH%
  - gradlew.bat clean
  - set JAVA_OPTS=-XX:MaxPermSize=1024m -Xmx1512m
build_script:
  - gradlew.bat -u -i clean assemble
test_script:
  - gradlew.bat -u -i -S test allSauceLabsTests
cache:
  - .gradle
  - C:\Users\appveyor\.gradle
on_failure:
  - echo It seems something went kaput
